project:
  type: website

website:
  title: "Sequencing ELR"
  navbar:
      left:
        - href: index.qmd
          text: Overview
        - pages/strengths.qmd
        - pages/flow.qmd
        - pages/wdrs.qmd
        - pages/drive.qmd
        - pages/example.qmd
        - pages/guidance.qmd
      right: 
        - icon: github
          href: https://github.com/NW-PaGe/covid_seq_elr
          target: _blank
        - icon: envelope
          href: mailto:DOH.CDS.GenSeqSurvDQ@doh.wa.gov
          target: _blank
        - icon: house-heart
          href: https://nwpage.org/
          target: _blank
      logo: images/logo.png
      link-external-newwindow: true
          
format:
  html:
    theme: minty
    backgroundcolor: "#fdfcfb"
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^.*nw-page.github.io.*|^.*NW-PaGe.github.io.*'
    highlight-style: dracula
